### ISSUE TITLE
'Keyboard' object has no attribute 'name'

### ISSUE THREAD

**Issue by antonagestam** [zeth/inputs#13]
Using the example from the readme in a file called devices.py, I stumbled on an AttributeError.

```python
from inputs import devices

for device in devices:
    print(device)
```

```
$ python devices.py
Traceback (most recent call last):
  File "devices.py", line 4, in <module>
    print(device)
  File "/Users/agestuds/python_projects/controller/.controller/lib/python3.5/site-packages/inputs.py", line 2031, in __str__
    return self.name
AttributeError: 'Keyboard' object has no attribute 'name'
```

Using macOS Sierra (10.12.3) and with inputs and pyobjc installed in a virtualenv with python version 3.5.2.

**Comment by BrianRamsay** [comment]
Same issue for me, with El Capitan, on python 2.7 or 3

**Comment by ctmrocks2435** [comment]
I also have this error running Win7 - Python 3.5
Anyone find a solution?

**Comment by Slippersen** [comment]
I am experiencing the same issue. 
Windows 10 - Python 3.6.1.
