### ISSUE TITLE
A simple fix for OLD code paths.

### ISSUE THREAD

**Issue by hardkrash** [zeth/inputs#14]
In `iter_unpack` The code is always checking `OLD`  it would be better to change this to:
```python
if OLD:
    def iter_unpack(raw):
        """Yield successive 24-sized chunks from message."""
            return chunks(raw)
else:
    def iter_unpack(raw):
        """Yield successive 24-sized chunks from message."""
            return struct.iter_unpack(EVENT_FORMAT, raw)
```

Now the OLD vs NEW check is only performed at file load, not on each function call.

Sorry for not making a pull request.

**Comment by zeth** [comment]
Thanks very much, good tip.
