### ISSUE TITLE
Generic Xbox 360 (Afterglow) not being detected

### ISSUE THREAD

**Issue by millerda** [zeth/inputs#16]
After finding the device id using `lsusb`, I can get my gamepad detected in `jstest-gtk` and the emulator I want to run using `xboxdrv`, but when I try to access it using `get_gamepad()` I get an error `inputs.UnpluggedError: No gamepad found`. I have a feeling it might be because inputs is looking for gamepads using the /dev/inputs/by-id/ entry, but my gamepad does not have a corresponding entry there (shows up as /dev/inputs/js3 and /dev/inputs/event8 however).

Seems like if it is detected by jstest and my emulator it should be able to work with inputs.

Any ideas?

**Comment by zeth** [comment]
Which distribution is this? Try again please with inputs 0.2 and re-open issue if it doesn't fix it for you.
