### ISSUE TITLE
MacOsX

### ISSUE THREAD

**Issue by augmen** [zeth/inputs#18]
Is your package is compatible with Mac ? Is thes is under active development ? do i need to install the pygames / piglet also ? what are the dependencies to connect it to the game and opencv ?

Do i require gamepad ? what are Gamepads alternatives for MacOSx ? as the mentioned game pads are not available for mac. Please guide

**Comment by zeth** [comment]
It is compatible with Mac for keyboard and mouse so far. If I remember rightly, some gamepads come through as keyboards on the mac, not sure about the rest. If you find out more, please let me know.
This is (again) under active development.
