### ISSUE TITLE
AttributeError: 'Keyboard' has no attribute 'name'

### ISSUE THREAD

**Issue by shotwn** [zeth/inputs#19]
PS C:\Desktop\inputs-master\examples> py .\devices_example.py
we found a gamepad.
We have detected the following devices:

Traceback (most recent call last):
  File ".\devices_example.py", line 18, in <module>
    main()
  File ".\devices_example.py", line 14, in main
    print(device)
  File "C:\Desktop\inputs-master\examples\inputs.py", line 2033, in __str__
    return self.name
AttributeError: 'Keyboard' object has no attribute 'name'
PS C:\Desktop\inputs-master\examples>

Finding this library was a spark of hope for me but sadly I couldn't make it function at python 3.6.1 Win10

**Comment by anilhaksever** [comment]
fixed it using a dummy self.name variable after line 2015.
Another problem has risen now, at mouse demo a click freezes the cursor

**Comment by zeth** [comment]
Fixed at https://github.com/zeth/inputs/pull/41
